### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by iosifnicolae2** [adinuca/vitamin-code-challenge#1]
I ran `npm install` then `npm start`
![image](https://user-images.githubusercontent.com/7108834/28360195-6e4df972-6c7d-11e7-852c-c766a27cb0ac.png)

**Comment by adinuca** [comment]
Imi spui te rog pe ce sistem de operare, ce versiune de node si npm?

**Comment by iosifnicolae2** [comment]
eu foloses Mac OS, imi poti spune te rog comenzile pe care trebuie sa le execut pt a afla aceste informatii?(prespun ca aceasta eroare va aparea unui client, iar acesta nu o sa stie sa raspunda la aceasta intrebare)

**Comment by adinuca** [comment]
npm -v pentru versiunea de npm
node -v pentru persiunea node

**Comment by iosifnicolae2** [comment]
```
Nicolaes-MBP:~ iosif$ npm -v
5.2.0
Nicolaes-MBP:~ iosif$ node -v
v8.1.3
Nicolaes-MBP:~ iosif$ 
```

**Comment by adinuca** [comment]
Mersi, voi incerca intr-un mediu curat cu versiunile tale, deoarece eu nu pot sa reproduc local.

**Comment by iosifnicolae2** [comment]
ok

**Comment by adinuca** [comment]
Poti te rog sa rulezi `npm -ls` sa vad ce pachete ai instalate. 
Deasemenea, poti te rog sa incerci sa rulezi `npm install --save-dev eslint-plugin-import` si apoi `npm start` sa vezi daca merge?
Am incercat pe o masina total curata, cu versiunile tale de node si npm si totul merge ok.

**Comment by adinuca** [comment]
scuze, din greseala am inchis-o.

**Comment by iosifnicolae2** [comment]
![image](https://user-images.githubusercontent.com/7108834/28365987-6f19c9ce-6c93-11e7-95b1-2f6cfb88f76b.png)

**Comment by iosifnicolae2** [comment]
a functionat, thanks!
